name: Static Website

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - uses: egordm/gha-yarn-node-cache@v1
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - run: |
        cd warehouse/web
        yarn install && yarn build
        cd ..
        go run ./main.go
    
    
