name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          cd warehouse/web
          yarn install && yarn build
          cd ..
          go run ./main.go
      - name: Run a multi-line script
        run: |
          cd warehouse
          go get -u github.com/onsi/ginkgo/ginkgo
          ginkgo -r -keepGoing .
      - name: Run a multi-line script
        run: |
          cd warehouse && yarn install && yarn test
