name: Static Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Go Modules
      uses: cedrickring/golang-action@1.6.0
      env:
        GO111MODULE: "on"
    - name: build APP
      run: |
        cd warehouse/web
        yarn install && yarn build
        cd ..
        go run ./main.go
    - name: Test Backend APP
      run: |
        cd warehouse && go get -u github.com/onsi/ginkgo/ginkgo && ginkgo -r -keepGoing .
    - name: Test Front End APP
      run: cd warehouse && yarn install && yarn test
