name: GO APP

on:
  push:
    branches:
    - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: |
        cd warehouse/web
        yarn install && yarn build
        cd ..
        go run ./main.go
    - run: |
        cd warehouse
        go get -u github.com/onsi/ginkgo/ginkgo
        ginkgo -r -keepGoing .
    - run: |
        cd warehouse && yarn install && yarn test
