name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: build
      uses: cedrickring/golang-action@1.6.0
      run: |
        cd warehouse/web
        yarn install && yarn build
        cd ..
        go run ./main.go
