name: GO APP

on:
  push:
    branches:
    - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
         node-version: '16'
      
    - run: cd warehouse/web && yarn install
    - run: cd warehouse/web && yarn build
    - run: cd warehouse && go run ./main.go
      
    - run: |
        cd warehouse
        go get -u github.com/onsi/ginkgo/ginkgo
        ginkgo -r -keepGoing .
        
    - run: |
        cd warehouse && yarn install && yarn test
