name: Static Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: build
      run: cd warehouse/web
      run: yarn install && yarn build
      run: cd ..
      run: go run ./main.go
