name: Static Website

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Install && Build
      run: |
        cd warehouse/web
        yarn install && yarn build
        cd ..
        go run ./main.go
