name: Static Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: build
      run: docker build -t dutyfree .
      run: docker run dutyfree -p 9090:9090
